"""
intent_examples.py
Examples per intent for semantic intent detection.
The model embeds these once at init.
"""
 
INTENT_EXAMPLES: dict[str, list[str]] = {
    "find_recipe": [
        "what can I make with chicken and garlic",
        "I have eggs and spinach at home",
        "what can I cook with what I have in the fridge",
        "recipe with carrots and potatoes",
        "available ingredients chicken tomatoes onion",
        "I only have some pasta and cheese",
        "what can I combine with salmon",
        "using leftovers from the fridge",
        "what food can I make with this",
        "I only have rice and vegetables",
        "what do I cook with these ingredients",
        "I have beef onion and peppers",
    ],
    "recipe_info": [
        "how do I make carbonara",
        "recipe for risotto",
        "how to prepare shakshuka",
        "explain how to make pad thai",
        "steps to make tiramisu",
        "how do I cook chicken breast",
        "full recipe for lasagna",
        "how do you make french onion soup",
        "show me how to cook ramen",
        "give me the recipe for tacos",
    ],
    "technique_info": [
        "what is braising",
        "explain the wok hei technique",
        "what does blanching mean",
        "how does emulsification work",
        "what is the maillard reaction",
        "explain deglazing",
        "what is confit",
        "how do you reduce a sauce",
        "what does sauteing mean",
        "explain tempering spices",
        "what is poaching",
    ],
    "substitution": [
        "what do I use instead of eggs",
        "substitute for butter",
        "I don't have cream what do I use",
        "alternative to parmesan",
        "no milk what can I use",
        "what replaces bacon",
        "I don't have wine for the recipe",
        "what do I use instead of honey",
        "no soy sauce what can I substitute",
        "replacement for flour",
    ],
    "dietary_filter": [
        "vegan recipes",
        "something vegetarian",
        "gluten free food",
        "dairy free recipes",
        "plant-based options",
        "food without meat",
        "keto recipes",
        "paleo diet recipes",
        "no animal products",
    ],
    "time_filter": [
        "something quick under 30 minutes",
        "fast recipe",
        "I want to cook quickly",
        "something simple in 20 minutes",
        "quick meal",
        "under an hour",
        "easy and fast recipe",
        "recipes under 15 minutes",
        "quick dinner ideas",
    ],
    "cuisine_filter": [
        "Italian recipes",
        "Thai food",
        "Indian cuisine",
        "something Japanese",
        "Mexican recipes",
        "Chinese food",
        "Mediterranean cuisine",
        "Korean recipes",
        "French food",
        "Middle Eastern recipes",
        "Greek food",
    ],
    "random_recipe": [
        "surprise me",
        "something random",
        "I don't know what to cook",
        "any recipe",
        "you choose for me",
        "whatever",
        "give me an idea",
        "random dish",
        "pick something for me",
    ],
    "help": [
        "help",
        "what can you do",
        "how do I use you",
        "what features do you have",
        "show me the commands",
        "what do you know how to do",
        "what are your capabilities",
    ],
    "chitchat_greet": [
        "hi",
        "hello",
        "hey",
        "good morning",
        "good evening",
        "howdy",
    ],
    "chitchat_thanks": [
        "thank you",
        "thanks",
        "great thanks",
        "awesome",
        "nice",
        "that's great",
        "perfect",
    ],
    "chitchat_identity": [
        "who are you",
        "what are you",
        "what's your name",
        "tell me about yourself",
        "are you a robot",
        "are you an AI",
    ],
    "chitchat_bye": [
        "bye",
        "goodbye",
        "see you",
        "later",
        "take care",
    ],
}