"""
intent_examples.py
Exemple per intenție pentru semantic intent detection.
Modelul le embedează o singură dată la init.
"""

INTENT_EXAMPLES: dict[str, list[str]] = {
    "find_recipe": [
        "ce pot face cu pui și usturoi",
        "am ouă și spanac acasă",
        "ce gătesc cu ce am în frigider",
        "rețetă cu morcovi și cartofi",
        "ingrediente disponibile pui roșii ceapă",
        "am doar niște paste și brânză",
        "ce combin cu somon",
        "folosesc resturile din frigider",
        "ce mâncare fac cu asta",
        "n-am decât orez și legume",
    ],
    "recipe_info": [
        "cum fac carbonara",
        "rețeta de risotto",
        "cum se prepară shakshuka",
        "explică-mi cum fac pad thai",
        "pași pentru a face tiramisu",
        "cum gătesc piept de pui",
        "rețeta completă de lasagna",
        "cum prepari supa de ceapă",
    ],
    "technique_info": [
        "ce este braising",
        "explică-mi tehnica wok hei",
        "ce înseamnă blanching",
        "cum funcționează emulsionarea",
        "ce este reacția maillard",
        "explică deglazing",
        "ce este confit",
        "cum se face reducția unui sos",
        "ce înseamnă a sota legumele",
    ],
    "substitution": [
        "ce pun în loc de ouă",
        "înlocuitor pentru unt",
        "nu am smântână ce folosesc",
        "alternativă la parmezan",
        "fără lapte ce pun",
        "înlocuiesc baconul cu ce",
        "nu am vin pentru rețetă",
        "ce folosesc în loc de miere",
        "fără sos de soia ce pun",
    ],
    "dietary_filter": [
        "rețete vegane",
        "ceva vegetarian",
        "mâncare fără gluten",
        "rețete fără lactate",
        "opțiuni plant-based",
        "mâncare fără carne",
        "rețete keto",
        "ceva paleo",
    ],
    "time_filter": [
        "ceva rapid sub 30 minute",
        "rețetă rapidă",
        "vreau să gătesc repede",
        "ceva simplu în 20 minute",
        "mâncare fast",
        "sub o oră",
        "rețetă ușoară și rapidă",
    ],
    "cuisine_filter": [
        "rețete italiene",
        "mâncare thai",
        "bucătărie indiană",
        "ceva japonez",
        "rețete mexicane",
        "mâncare chineză",
        "bucătărie mediteraneană",
        "rețete coreene",
        "ceva franțuzesc",
    ],
    "random_recipe": [
        "surprinde-mă",
        "ceva aleatoriu",
        "nu știu ce să gătesc",
        "orice rețetă",
        "alege tu pentru mine",
        "indiferent ce",
        "dă-mi o idee",
    ],
    "help": [
        "ajutor",
        "ce poți face",
        "cum te folosesc",
        "ce funcții ai",
        "arată-mi comenzile",
        "ce știi să faci",
    ],
    "chitchat_greet": [
        "salut",
        "bună ziua",
        "hello",
        "hey",
        "bună",
    ],
    "chitchat_thanks": [
        "mulțumesc",
        "mersi",
        "super mulțumesc",
        "grozav",
        "mișto",
    ],
    "chitchat_identity": [
        "cine ești",
        "ce ești tu",
        "cum te cheamă",
        "despre tine",
        "ești un robot",
    ],
    "chitchat_bye": [
        "pa",
        "la revedere",
        "bye",
        "pe curând",
    ],
}