"""
intent_examples.py
Intent examples for semantic intent detection.
The model embeds them once at startup.
"""

INTENT_EXAMPLES: dict[str, list[str]] = {
    "find_recipe": [
        "what can I make with chicken and garlic",
        "I have eggs and spinach at home",
        "what to cook with what I have in the fridge",
        "recipe with carrots and potatoes",
        "available ingredients chicken tomatoes onion",
        "I only have some pasta and cheese",
        "what goes well with salmon",
        "use the leftovers from the fridge",
        "what dish can I make with this",
        "I only have rice and vegetables",
    ],
    "recipe_info": [
        "how to make carbonara",
        "risotto recipe",
        "how to prepare shakshuka",
        "explain to me how to make pad thai",
        "steps to make tiramisu",
        "how to cook chicken breast",
        "full recipe for lasagna",
        "how do you prepare onion soup",
    ],
    "technique_info": [
        "what is braising",
        "explain to me the wok hei technique",
        "what does blanching mean",
        "how does emulsification work",
        "what is the maillard reaction",
        "explain deglazing",
        "what is confit",
        "how do you reduce a sauce",
        "what does it mean to sauté vegetables",
    ],
    "substitution": [
        "what can I use instead of eggs",
        "butter substitute",
        "I don't have sour cream what do I use",
        "alternative to parmesan",
        "what to use without milk",
        "what can I replace bacon with",
        "I don't have wine for the recipe",
        "what to use instead of honey",
        "what to use without soy sauce",
    ],
    "dietary_filter": [
        "vegan recipes",
        "something vegetarian",
        "gluten free food",
        "dairy free recipes",
        "plant based options",
        "food without meat",
        "keto recipes",
        "something paleo",
    ],
    "time_filter": [
        "something quick under 30 minutes",
        "quick recipe",
        "I want to cook quickly",
        "something simple in 20 minutes",
        "fast food recipe",
        "under an hour",
        "easy and quick recipe",
    ],
    "cuisine_filter": [
        "italian recipes",
        "thai food",
        "indian cuisine",
        "something japanese",
        "mexican recipes",
        "chinese food",
        "mediterranean cuisine",
        "korean recipes",
        "something french",
    ],
    "random_recipe": [
        "surprise me",
        "something random",
        "I don't know what to cook",
        "any recipe",
        "choose for me",
        "whatever",
        "give me an idea",
    ],
    "help": [
        "help",
        "what can you do",
        "how to use you",
        "what functions do you have",
        "show me the commands",
        "what do you know how to do",
    ],
    "chitchat_greet": [
        "hello",
        "hi",
        "hey",
        "good morning",
        "welcome",
    ],
    "chitchat_thanks": [
        "thanks",
        "thank you",
        "thank you so much",
        "great",
        "awesome",
        "perfect",
    ],
    "chitchat_identity": [
        "who are you",
        "what are you",
        "what is your name",
        "about you",
        "are you a robot",
    ],
    "chitchat_bye": [
        "bye",
        "goodbye",
        "see you later",
        "see ya",
    ],
}